/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSLock, NSMutableArray;

@interface SBAccelerometerInterface : NSObject
{
    NSLock *_lock;
    double _samplingInterval;
    double _topDisplayLastUpdateTime;
    double _topDisplayInterval;
    NSMutableArray *_clients;
}

+ (void)initialize;
+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)updateSettings;
- (void)clientRequestedAccelerometerEvents:(unsigned int)fp8 updateInterval:(double)fp12 xThreshold:(float)fp20 yThreshold:(float)fp24 zThreshold:(float)fp28 auditToken:(CDAnonymousStruct3 *)fp32;
- (void)_clientInvalidated:(id)fp8;
- (void)accelerometerDataReceived:(double)fp8 x:(float)fp16 y:(float)fp20 z:(float)fp24 type:(unsigned int)fp28;

@end

