/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class CPAggregateDictionary, NSString, NSTimer;

@interface SBAggregateDCommunicator : NSObject
{
    CPAggregateDictionary *_dictionary;
    NSTimer *_periodicFlushTimer;
    NSString *_lastApplicationActivatedIdentifier;
    double _lastApplicationActivatedTime;
    double _backlightOnStartTime;
    BOOL _backlightOnStartTimeWasOnBattery;
    BOOL _backlightOnStartTimeIsValid;
    double _awakeTimeStart;
    BOOL _awakeTimeStartWasOnBattery;
    BOOL _awakeTimeStartIsValid;
    int _lastConnectionType;
    double _lastConnectionTime;
    BOOL _lastConnectionTimeIsValid;
    double _vpnUsageStartTime;
    BOOL _vpnUsageStartTimeIsValid;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)reportNumberOfIcons:(int)fp8;
- (void)reportApplicationLaunched:(id)fp8 isSystemApplication:(BOOL)fp12;
- (void)reportApplicationActivated:(id)fp8 isSystemApplication:(BOOL)fp12;
- (void)reportApplicationDeactivated:(id)fp8 isSystemApplication:(BOOL)fp12;
- (void)_batteryStatusChanged:(id)fp8;
- (void)reportScreenHasDimmed;
- (void)reportScreenHasUndimmed;
- (void)_forceUpdateBacklightTimers;
- (void)reportDeviceHasAwoken;
- (void)reportDeviceWillSleep;
- (void)_forceUpdateAwakeTimers;
- (void)reportCallDuration:(double)fp8 connectionType:(int)fp16;
- (void)reportConnectionTypeChanged;
- (void)_forceUpdateConnectionTypeTimers;
- (void)reportVPNStatusChanged;
- (void)_startVPNConnectionTimer;
- (void)_stopVPNConnectionTimer;
- (void)_forceUpdateVPNConnectionTimer;
- (void)_forceUpdateAllTimers:(id)fp8;

@end

