/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class NSMutableArray;

@interface SBAppRatingsStarControl : UIControl
{
    NSMutableArray *_stars;
    int _currentIndex;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (float)firstStarOffset;
- (void)layoutSubviews;
- (void)handleTouches:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (int)currentIndex;

@end

