/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSOperation.h>

@class NSString;

@interface SBApplicationUninstallationOperation : NSOperation
{
    NSString *_bundleIdentifier;
}

- (id)initWithBundleIdentifier:(id)fp8;
- (void)dealloc;
- (void)main;

@end

