/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSOperationQueue, SBApplication;

@interface SBApplicationController : NSObject
{
    NSDictionary *_pendingApplicationDictionaries;
    NSMutableDictionary *_applications;
    NSMutableDictionary *_applicationsByBundleIdentifer;
    SBApplication *_springBoard;
    unsigned int _ignoreUninstallationEventCount;
    NSOperationQueue *_backgroundOperationQueue;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)allApplications;
- (id)applicationsWithBundleIdentifier:(id)fp8;
- (id)applicationWithDisplayIdentifier:(id)fp8;
- (id)applicationWithPid:(int)fp8;
- (id)springBoard;
- (id)iPod;
- (id)loadApplications;
- (void)loadApplicationsAndIcons:(id)fp8 reveal:(BOOL)fp12 popIn:(BOOL)fp16;
- (void)removeApplicationsFromModelWithBundleIdentifier:(id)fp8;
- (void)uninstallApplication:(id)fp8;
- (void)waitForOperationsToComplete;
- (Class)applicationClassForBundleIdentifier:(id)fp8;
- (void)loadRolesWithBundle:(id)fp8 bundlePath:(id)fp12 isSystemApplication:(BOOL)fp16 defaultTags:(id)fp20 signerIdentity:(id)fp24 provisioningProfileValidated:(BOOL)fp28 seatbeltEnvironmentVariables:(id)fp32;
- (void)updateSchemesForRoleDefinition:(id)fp8 displayIdentifier:(id)fp12 application:(id)fp16;
- (id)rolesForInfoPlist:(id)fp8;
- (id)rolesForRoleDefinitions:(id)fp8;
- (id)displayNameForInfoDictionary:(id)fp8 inBundle:(id)fp12;
- (id)widgetRoles;
- (void)_applicationInstallationCallback:(id)fp8;
- (void)_handleInstalledApplicationDictionaryIfReceived;
- (void)processPendingInstalls;
- (id)pendingApplicationDictionaries;
- (void)setPendingApplicationDictionaries:(id)fp8;

@end

