/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface SBAppContextHostView : UIView
{
    NSMutableArray *_contexts;
    BOOL _hostingEnabled;
}

- (id)initWithDefaultSize;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)description;
- (BOOL)isHostingEnabled;
- (void)setHostingEnabled:(BOOL)fp8;
- (void)willOrderInContextWithId:(unsigned int)fp8 windowLevel:(float)fp12 windowOutput:(int)fp16;
- (void)didOrderOutContextWithId:(unsigned int)fp8;
- (void *)createIOSurfaceForFrame:(struct CGRect)fp8;
- (void *)createIOSurfaceForFrame:(struct CGRect)fp8 includeAdditionalContext:(unsigned int)fp24;

@end

