/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBAlert.h>

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSTimeZone, NSTimer, SBAlertItem, SBAwayModel, SBAwayView, SBSleepProofTimer, SBSlidingAlertDisplay, SBUIController;

@interface SBAwayController : SBAlert
{
    SBUIController *_uiController;
    SBAwayModel *_model;
    SBAwayView *_awayView;
    NSTimer *_dimTimer;
    unsigned int _isLocked:1;
    unsigned int _isDeviceLocked:1;
    unsigned int _isDeviceLockedInitialized:1;
    unsigned int _isDimmed:1;
    unsigned int _isDimming:1;
    unsigned int _orderedOutDimmed:1;
    unsigned int _frontDimmed:1;
    unsigned int _isPermanentlyBlocked:1;
    unsigned int _makingEmergencyCall:1;
    unsigned int _appRequestedPasscodeEntry:1;
    unsigned int _isSyncing:1;
    unsigned int _relockAfterUnlock:1;
    unsigned int _wasLockedOrMakingEmergencyCallBeforeSync:1;
    unsigned int _wasDeviceLockedBeforeSync:1;
    unsigned int _showOverheatUI:1;
    NSDictionary *_nowPlayingInfo;
    SBSlidingAlertDisplay *_deviceUnlockDisplay;
    double _deviceLockBlockTime;
    double _lastLockWallTime;
    NSTimeZone *_lastLockTimeZone;
    double _lastLockSecondsSinceBoot;
    NSTimer *_deviceLockTimer;
    BOOL _devicePasscodeLoaded;
    NSString *_devicePasscode;
    NSMutableArray *_pendingAlertItems;
    SBAlertItem *_currentAlertItem;
    NSMutableDictionary *_awayViewPluginControllers;
    SBSleepProofTimer *_smsSoundWakeTimers[2];
}

+ (id)sharedAwayController;
+ (void)registerForAlerts;
- (id)initWithUIController:(id)fp8;
- (id)awayModel;
- (struct CGRect)alertWindowRect;
- (float)finalAlpha;
- (BOOL)undimsDisplay;
- (id)awayView;
- (id)alertDisplayViewWithSize:(struct CGSize)fp8;
- (void)alertDisplayWillBecomeVisible;
- (void)dealloc;
- (void)_releaseAwayView;
- (void)reactivatePendingAlertItems;
- (void)playLockSound;
- (void)_sendLockStateChangedNotification;
- (BOOL)showOverheatUI;
- (void)setShowOverheatUI:(BOOL)fp8;
- (void)_pendAlertItem:(id)fp8;
- (void)lock;
- (id)pendingAlertItems;
- (void)_unlockWithSound:(BOOL)fp8;
- (void)unlockWithSound:(BOOL)fp8;
- (void)unlockWithSound:(BOOL)fp8 alertDisplay:(id)fp12;
- (void)loadPasscode;
- (id)devicePasscode;
- (BOOL)isPasswordProtected;
- (void)activationChanged:(id)fp8;
- (BOOL)isDeviceLockedOrBlocked;
- (void)setDeviceLocked:(BOOL)fp8;
- (int)_getGracePeriod;
- (void)_markLockTime;
- (void)_updateDeviceLockedState;
- (void)clearDeviceLockedTimer;
- (void)applicationRequestedDeviceUnlock;
- (void)cancelApplicationRequestedDeviceLockEntry;
- (void)_clearBlockedState;
- (BOOL)isBlocked;
- (BOOL)isPermanentlyBlocked:(double *)fp8;
- (void)noteSyncStateChanged;
- (BOOL)isSyncing;
- (void)noteResetRestoreStateChanged;
- (BOOL)isLocked;
- (BOOL)shouldShowLockStatusBarTime;
- (void)lockBarStartedTracking:(id)fp8;
- (void)lockBarStoppedTracking:(id)fp8;
- (void)resetAwayItems;
- (void)frontLockedAnimationFinished;
- (BOOL)shouldAnimateOtherDisplaysSuspension;
- (BOOL)shouldAnimateOtherDisplaysResumption;
- (void)printLockLog;
- (void)frontLocked:(BOOL)fp8 animate:(BOOL)fp12 automatically:(BOOL)fp16;
- (void)attemptUnlock;
- (BOOL)isAttemptingUnlock;
- (void)_finishedUnlockAttemptWithStatus:(BOOL)fp8;
- (BOOL)attemptDeviceUnlockWithPassword:(id)fp8 alertDisplay:(id)fp12;
- (void)cancelDimTimer;
- (void)restartDimTimer:(float)fp8;
- (id)dimTimer;
- (BOOL)isDimmed;
- (void)finishedDimmingScreen;
- (BOOL)moveAlertItemToAwayView:(id)fp8;
- (void)cleansePendingQueueOfAwayItems;
- (void)smsMessageReceived;
- (void)cancelScheduledSMSSounds;
- (void)_smsSoundWakeTimerFired:(id)fp8;
- (void)dimTimerFired;
- (void)relockForButtonPress:(BOOL)fp8 afterCall:(BOOL)fp12;
- (void)relockForButtonPress:(BOOL)fp8 afterCall:(BOOL)fp12 dimmed:(BOOL)fp16;
- (void)allowIdleSleep;
- (void)preventIdleSleep;
- (void)preventIdleSleepForNumberOfSeconds:(float)fp8;
- (void)dimScreen:(BOOL)fp8;
- (void)_undimScreen;
- (void)undimScreen;
- (void)userEventOccurred;
- (void)activate;
- (void)deactivate;
- (BOOL)allowsStackingOfAlert:(id)fp8;
- (BOOL)allowsDoubleHeightStatusBar:(BOOL)fp8;
- (int)statusBarMode;
- (void)orderOut;
- (void)didFinishAnimatingOut;
- (void)updateNowPlayingInfo:(id)fp8;
- (void)handleRequestedAlbumArt:(id)fp8;
- (void)updateClockFormat;
- (void)makeEmergencyCall;
- (void)emergencyCallWasDisplayed;
- (void)emergencyCallWasRemoved;
- (BOOL)isMakingEmergencyCall;
- (void)didAnimateLockKeypadIn;
- (void)didAnimateLockKeypadOut;
- (id)currentAlertItem;
- (void)pendOrDeactivateCurrentAlertItem;
- (BOOL)isCurrentAlertItemRinging;
- (BOOL)attemptSnoozeRingingAlertItem;
- (void)stopRingingAlertItem;
- (void)snoozeOrStopRingingAlertItem;
- (BOOL)activateAlertItem:(id)fp8;
- (BOOL)wantsToHandleAlert:(id)fp8;
- (void)deactivateAlertItem:(id)fp8;
- (void)updateInCallUI;
- (BOOL)isShowingMediaControls;
- (void)hideMediaControls;
- (BOOL)toggleMediaControls;
- (void)toggleShowsIMEIandICCID:(id)fp8;
- (BOOL)isAwayPluginViewVisible;
- (id)highestPriorityAwayPluginController;
- (void)enableLockScreenBundleWithName:(id)fp8;
- (void)disableLockScreenBundleWithName:(id)fp8;
- (void)disablePluginContainerNotification:(id)fp8;
- (BOOL)awayPluginControllerShouldAnimateOthersResumption;
- (BOOL)handleMenuButtonTap;
- (BOOL)handleMenuButtonDoubleTap;
- (BOOL)handleMenuButtonHeld;

@end

