/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString, NSTimer, SBAwayMediaControlsView, TPLCDTextView, UILabel;

@interface SBAwayDateView : UIView
{
    NSTimer *_dateTimer;
    TPLCDTextView *_timeLabel;
    TPLCDTextView *_titleLabel;
    NSString *_title;
    NSString *_artist;
    NSString *_album;
    UILabel *_nowPlayingTitleLabel;
    UILabel *_nowPlayingArtistLabel;
    UILabel *_nowPlayingAlbumLabel;
    SBAwayMediaControlsView *_controlsView;
    id _delegate;
    unsigned int _isPlaying:1;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)labelWithFontSize:(float)fp8 origin:(struct CGPoint)fp12 fontName:(const char *)fp20;
- (id)labelWithFontSize:(float)fp8 origin:(struct CGPoint)fp12;
- (id)newNowPlayingLabelWithFont:(id)fp8 color:(id)fp12 origin:(struct CGPoint)fp16;
- (void)updateLabels;
- (void)setAlpha:(float)fp8;
- (void)updateClockFormat;
- (void)updateClock;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setArtist:(id)fp8;
- (void)setAlbum:(id)fp8;
- (void)removeFromSuperview;
- (void)movedToSuperview:(id)fp8;
- (id)controlsView;
- (void)setIsShowingControls:(BOOL)fp8;
- (BOOL)isShowingControls;
- (void)setPlaying:(BOOL)fp8;
- (BOOL)isPlaying;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

