/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBIcon.h>

@class UIWebClip;

@interface SBBookmarkIcon : SBIcon
{
    UIWebClip *_webClip;
}

- (id)initWithWebClip:(id)fp8;
- (void)dealloc;
- (BOOL)allowsCloseBox;
- (id)icon;
- (id)displayName;
- (id)displayIdentifier;
- (id)modificationDate:(BOOL)fp8;
- (void)launch;
- (void)completeUninstall;
- (id)webClip;

@end

