/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface SBCFBundle : NSObject
{
    struct __CFBundle *_cfBundle;
}

- (id)initWithPath:(id)fp8;
- (id)initWithCFBundle:(struct __CFBundle *)fp8;
- (void)dealloc;
- (id)executablePath;
- (id)bundleIdentifier;
- (id)pathForResource:(id)fp8 ofType:(id)fp12;
- (id)localizedStringForKey:(id)fp8 value:(id)fp12 table:(id)fp16;
- (id)infoDictionary;
- (id)localizedInfoDictionary;

@end

