/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, SBCompassRecalibrationView, UIWindow;

@interface SBCompassRecalibrationController : NSObject
{
    NSMutableArray *_assertionPorts;
    UIWindow *_recalibrationWindow;
    SBCompassRecalibrationView *_recalibrationView;
}

+ (id)sharedInstance;
+ (BOOL)isCompassCalibrationWindowVisible;
- (id)init;
- (void)showHUD;
- (void)_createUI;
- (void)reorientRecalibrationHUDIfNeeded:(BOOL)fp8;
- (void)removeHUD;
- (void)_animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_tearDown;
- (void)clientRequestedCompassHUD:(unsigned int)fp8;
- (void)_clientInvalidated:(struct __CFMachPort *)fp8;

@end

