/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class CALayerHost;

@interface SBContext : NSObject
{
    unsigned int _contextId;
    float _windowLevel;
    CALayerHost *_layerHost;
}

- (void)dealloc;
- (id)description;
- (id)layerHost;
- (void)setLayerHost:(id)fp8;
- (float)windowLevel;
- (void)setWindowLevel:(float)fp8;
- (unsigned int)contextId;
- (void)setContextId:(unsigned int)fp8;

@end

