/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBIcon.h>

#import <iTunesStore/ISDownloadDelegate-Protocol.h>

@class ISDownload, ISDownloadStatus, NSString, SBDownloadingProgressBar;

@interface SBDownloadingIcon : SBIcon <ISDownloadDelegate>
{
    NSString *_displayID;
    NSString *_bundleID;
    ISDownload *_download;
    SBDownloadingProgressBar *_progressView;
    float _progress;
    BOOL _installing;
    BOOL _wasUninstalledByUser;
    ISDownloadStatus *_lastStatus;
}

+ (id)displayIdentifierForDownloadUniqueID:(id)fp8;
+ (id)displayIdentifierForDownload:(id)fp8;
- (id)initWithDisplayIdentifier:(id)fp8;
- (id)initWithDownload:(id)fp8;
- (void)dealloc;
- (id)description;
- (void)setDisplayIdentifier:(id)fp8;
- (id)icon;
- (id)modificationDate:(BOOL)fp8;
- (void)setDisplayedIcon:(id)fp8;
- (void)updateDisplayName;
- (BOOL)shouldEllipsizeLabel;
- (BOOL)shouldKernLabel;
- (id)displayName;
- (id)displayIdentifier;
- (void)launch;
- (BOOL)allowsCloseBox;
- (void)closeBoxClicked:(id)fp8;
- (void)completeUninstall;
- (void)download:(id)fp8 encounteredError:(id)fp12;
- (void)download:(id)fp8 loadedArtworkImage:(struct CGImage *)fp12;
- (void)downloadStatusChanged:(id)fp8;
- (id)bundleID;
- (void)setBundleID:(id)fp8;
- (void)setDownload:(id)fp8;
- (id)download;
- (void)retry;
- (void)remove;
- (id)uninstallAlertTitle;
- (id)uninstallAlertBody;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertCancelTitle;
- (void)_reloadIcon;
- (void)_showAlertForError:(id)fp8;

@end

