/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface SBDoubleHeightStatusInfo : NSObject
{
    int _doubleHeightMode;
    int _priority;
    NSString *_prefixText;
    NSString *_statusText;
    NSString *_bundleID;
}

- (int)compareDoubleHeightInfos:(id)fp8;
- (void)dealloc;
- (int)priority;
- (void)setPriority:(int)fp8;
- (id)bundleID;
- (void)setBundleID:(id)fp8;
- (id)statusText;
- (void)setStatusText:(id)fp8;
- (id)prefixText;
- (void)setPrefixText:(id)fp8;
- (int)doubleHeightMode;
- (void)setDoubleHeightMode:(int)fp8;

@end

