/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIPushButton.h>

@interface SBEmergencyCallButton : UIPushButton
{
}

+ (id)defaultFont;
- (void)drawTitleInRect:(struct CGRect)fp8;
- (void)drawButtonPart:(int)fp8 inRect:(struct CGRect)fp12;

@end

