/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBAlertItem.h>

@class UIModalView;

@interface SBFlippyAlertItem : SBAlertItem
{
    UIModalView *_frontAlertSheet;
    UIModalView *_backAlertSheet;
    BOOL _showingBack;
    BOOL _isLocked;
    BOOL _requirePasscode;
}

- (Class)frontAlertSheetClass;
- (Class)backAlertSheetClass;
- (Class)alertSheetClass;
- (id)createFrontAlertSheet;
- (id)createBackAlertSheet;
- (id)frontAlertSheet;
- (id)backAlertSheet;
- (id)alertSheet;
- (void)dealloc;
- (void)cleanPreviousConfiguration;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)configureFront:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)configureBack:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)flip;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;

@end

