/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSSet, SBButtonBar, SBImageCache;

@interface SBIconModel : NSObject
{
    NSDictionary *_previousIconState;
    NSMutableArray *_iconLists;
    SBButtonBar *_buttonBar;
    NSMutableDictionary *_allIcons;
    NSSet *_hiddenIconTags;
    NSSet *_visibleIconTags;
    SBImageCache *_iconImageCache;
    SBImageCache *_smallIconImageCache;
}

+ (id)sharedInstance;
+ (int)maxIconListCount;
- (id)init;
- (void)dealloc;
- (void)localeChanged;
- (void)setVisibilityOfIconsWithVisibleTags:(id)fp8 hiddenTags:(id)fp12;
- (BOOL)isIconVisible:(id)fp8;
- (void)replaceDownloadingDisplayIdentifiers:(id)fp8 withDisplayIdentifiers:(id)fp12;
- (void)_completedUninstall:(id)fp8;
- (id)addDownloadingIconForDownload:(id)fp8;
- (id)addDownloadingIconForDisplayIdentifier:(id)fp8;
- (void)removeAppForDownloadingIcon:(id)fp8;
- (id)_addBookmarkIconForWebClip:(id)fp8;
- (id)addBookmarkIconForWebClip:(id)fp8;
- (void)reloadIconImage:(id)fp8;
- (void)reloadIconImageForDisplayIdentifier:(id)fp8;
- (void)_purgeAndSaveCachedImages;
- (void)_purgeAndSaveCachedImages:(id)fp8;
- (void)cacheImagesForIcon:(id)fp8;
- (void)_cacheImagesForIcon:(id)fp8 small:(BOOL)fp12;
- (id)getCachedImagedForIcon:(id)fp8 smallIcon:(BOOL)fp12;
- (void)_addIconForApplication:(id)fp8;
- (void)addIconForApplication:(id)fp8;
- (void)loadAllIcons;
- (id)visibleIconIdentifiers;
- (id)allIcons;
- (id)iconForDisplayIdentifier:(id)fp8;
- (id)iconState;
- (id)_iconState;
- (void)noteIconStateChangedExternally;
- (id)buttonBar;
- (id)iconLists;
- (int)indexOfIconList:(id)fp8;
- (void)createIconLists;
- (void)uninstallBookmarkIcon:(id)fp8;
- (id)iconListContainingIcon:(id)fp8;
- (id)iconListContainingIconWithDisplayIdentifier:(id)fp8;
- (id)addEmptyIconList;
- (void)removeEmptyIconList:(id)fp8;
- (void)compactIconLists;
- (id)firstAvailableIconListX:(int *)fp8 Y:(int *)fp12;
- (BOOL)iconPositionInPlatformState:(id)fp8 X:(int *)fp12 Y:(int *)fp16 inIconListNumber:(int *)fp20;
- (void)clearPreviousIconState;
- (void)addNewIconToDesignatedLocation:(id)fp8 animate:(BOOL)fp12 scrollToList:(BOOL)fp16 saveIconState:(BOOL)fp20;
- (void)_addNewIconToDesignatedLocation:(id)fp8 animate:(BOOL)fp12 scrollToList:(BOOL)fp16 saveIconState:(BOOL)fp20;
- (BOOL)_iconListsAreDirty;
- (void)deleteIconState;
- (void)_writeIconState;
- (void)saveIconState;
- (void)_replaceAppIconsWithDownloadingIcons;
- (void)_replaceAppIconWithDownloadingIcon:(id)fp8 sourceList:(id)fp12;
- (void)relayout;
- (void)uninstallApplicationIcon:(id)fp8;

@end

