/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString;

@interface SBIconBadge : UIView
{
    NSString *_badge;
    struct CGSize _badgeContentSize;
    BOOL _highlighted;
}

- (id)initWithBadge:(id)fp8;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (void)setHightlighted:(BOOL)fp8;

@end

