/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSTimer, SBIconBadge, SBIconImageView, SBIconLabel, UIImageView, UIPushButton;

@interface SBIcon : UIView
{
    SBIconImageView *_image;
    UIImageView *_reflection;
    UIView *_grayFilterView;
    SBIconBadge *_badge;
    id _badgeNumberOrString;
    SBIconLabel *_label;
    UIPushButton *_closeBox;
    unsigned int _isShowingImages:1;
    unsigned int _drawsLabel:1;
    unsigned int _isHidden:1;
    unsigned int _isRevealable:1;
    unsigned int _inDock:1;
    unsigned int _isGrabbed:1;
    unsigned int _isGrabbing:1;
    unsigned int _highlighted:1;
    unsigned int _isJittering:1;
    unsigned int _allowJitter:1;
    unsigned int _touchDownInIcon:1;
    NSTimer *_delayedUnhighlightTimer;
    struct CGPoint _unjitterPoint;
    struct CGPoint _grabPoint;
    NSTimer *_grabTimer;
}

+ (struct CGSize)defaultIconSize;
+ (void)enqueueReusableIconImageView:(id)fp8;
+ (id)dequeueReusableIconImageView;
+ (id)_jitterPositionAnimation;
+ (id)_jitterTransformAnimation;
- (id)initWithDefaultSize;
- (void)dealloc;
- (void)localeChanged;
- (void)showIconAnimationDidStop:(id)fp8 didFinish:(id)fp12 icon:(id)fp16;
- (void)setIsHidden:(BOOL)fp8 animate:(BOOL)fp12;
- (BOOL)isHidden;
- (void)setIsRevealable:(BOOL)fp8;
- (BOOL)isRevealable;
- (id)displayName;
- (int)localizedCompareDisplayNames:(id)fp8;
- (id)displayIdentifier;
- (id)modificationDate:(BOOL)fp8;
- (id)tags;
- (BOOL)launchEnabled;
- (void)setDisplayedIcon:(id)fp8;
- (id)icon;
- (id)smallIcon;
- (struct CGContext *)_createIconImageBitmapContextForSmallIcon:(BOOL)fp8;
- (id)reflectedIcon:(BOOL)fp8;
- (BOOL)isShowingImages;
- (void)setShowsImages:(BOOL)fp8;
- (void)updateLabelOrigin;
- (BOOL)shouldEllipsizeLabel;
- (BOOL)shouldKernLabel;
- (void)setDrawsLabel:(BOOL)fp8;
- (void)updateLabelKerningAndEllipsing;
- (int)badgeValue;
- (void)setBadge:(id)fp8;
- (id)_automationID;
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (id)darkenedIcon:(id)fp8 alpha:(float)fp12;
- (BOOL)isHighlighted;
- (void)setHighlighted:(BOOL)fp8;
- (void)setHighlighted:(BOOL)fp8 delayUnhighlight:(BOOL)fp12;
- (void)_delayedUnhighlight;
- (void)setInDock:(BOOL)fp8;
- (BOOL)isInDock;
- (void)setOrigin:(struct CGPoint)fp8;
- (void)setIsJittering:(BOOL)fp8;
- (void)setAllowJitter:(BOOL)fp8;
- (BOOL)allowJitter;
- (void)removeAllIconAnimations;
- (void)setIconPosition:(struct CGPoint)fp8;
- (double)grabDurationForEvent:(id)fp8;
- (void)setIsGrabbed:(BOOL)fp8;
- (BOOL)_shouldLockItemsInStoreDemoMode;
- (void)grabTimerFired;
- (void)cancelGrabTimer;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (id)dictionaryRepresentation;
- (void)launch;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (BOOL)allowsCloseBox;
- (void)hideCloseBoxAnimationDidStop:(id)fp8 didFinish:(id)fp12 closeBox:(id)fp16;
- (void)setIsShowingCloseBox:(BOOL)fp8;
- (BOOL)isShowingCloseBox;
- (void)closeBoxClicked:(id)fp8;
- (void)completeUninstall;
- (id)description;
- (id)uninstallAlertTitle;
- (id)uninstallAlertBody;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertCancelTitle;

@end

