/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import <SpringBoard/SBIconListPageControlDelegate-Protocol.h>
#import <UIKit/UIScrollViewDelegate-Protocol.h>

@class NSTimer, SBIcon, SBIconList, SBIconListPageControl, SBIconModel, SBIconScrollView, SBSearchView, TPLCDTextView, UITouch, UIView;

@interface SBIconController : NSObject <UIScrollViewDelegate, SBIconListPageControlDelegate>
{
    SBIconModel *_iconModel;
    UIView *_contentView;
    SBIconScrollView *_scrollView;
    SBIconListPageControl *_pageControl;
    int _currentIconListIndex;
    int _currentColumnIndex;
    TPLCDTextView *_idleText;
    float _currentIdleTextOffset;
    SBSearchView *_searchView;
    SBIcon *_lastClickedIcon;
    double _lastClickedTime;
    SBIcon *_iconToInstall;
    SBIcon *_grabbedIcon;
    SBIconList *_grabbedIconList;
    int _grabbedX;
    int _grabbedY;
    SBIcon *_swappedIcon;
    SBIconList *_swappedIconList;
    int _swappedX;
    int _swappedY;
    SBIconList *_destinationIconList;
    int _destinationX;
    int _destinationY;
    NSTimer *_scrollPageTimer;
    unsigned int _didScroll:1;
    unsigned int _isEditing:1;
    unsigned int _compacted:1;
    unsigned int _willSwap:1;
    unsigned int _animatedScrolling:1;
    unsigned int _scrollingToSearch:1;
    unsigned int _movedFromOrigin:1;
    float _iconAlpha;
    float _searchViewAlpha;
    UITouch *_lastTouch;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)contentView;
- (void)setPageControlVisible:(BOOL)fp8;
- (void)showInfoAlertIfNeeded;
- (void)showCarrierDebuggingAlertIfNeeded;
- (BOOL)isScrolling;
- (void)pageControl:(id)fp8 didRecieveTouchInDirection:(int)fp12;
- (int)lowestVisibleIconListIndexAndColumnIndex:(int *)fp8;
- (void)updateCurrentIconListIndex;
- (void)resetCurrentVisibleIconListImageVisibilityAndJitterState;
- (id)currentIconList;
- (BOOL)isShowingSearch;
- (int)currentIconListIndex;
- (void)scrollToIconListContainingIcon:(id)fp8 animate:(BOOL)fp12;
- (void)scrollToIconListAtIndex:(int)fp8 animate:(BOOL)fp12;
- (void)updateContentSize;
- (void)noteNumberOfIconListsChanged;
- (void)removeEmptyIconList:(id)fp8 animate:(BOOL)fp12;
- (id)iconToInstall;
- (void)setIconToInstall:(id)fp8;
- (void)finishInstallingIcon;
- (void)scrollToIconDestination;
- (id)addIcon:(id)fp8 toIconList:(id)fp12 x:(int)fp16 y:(int)fp20 animate:(BOOL)fp24 moveNow:(BOOL)fp28 scrollToList:(BOOL)fp32;
- (id)insertIcon:(id)fp8 intoIconList:(id)fp12 X:(int)fp16 Y:(int)fp20 moveNow:(BOOL)fp24 duration:(float)fp28;
- (void)removeIcon:(id)fp8 animate:(BOOL)fp12;
- (void)uninstallIconDidAnimate:(id)fp8 finished:(id)fp12 icon:(id)fp16;
- (void)uninstallIcon:(id)fp8;
- (void)uninstallIcon:(id)fp8 animate:(BOOL)fp12;
- (void)lcdTextViewCompletedScroll:(id)fp8;
- (void)idleTextDidAnimate:(id)fp8 finished:(id)fp12 toText:(id)fp16;
- (void)updateNumberOfRowsWithDuration:(float)fp8;
- (BOOL)hasIdleModeText;
- (void)setIdleModeText:(id)fp8;
- (void)scatter:(BOOL)fp8 startTime:(double)fp12;
- (void)unscatter:(BOOL)fp8 startTime:(double)fp12;
- (void)adjustIconListAlpha;
- (void)_showSearchKeyboardIfNecessary:(BOOL)fp8;
- (void)scrollViewDidScroll:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewWillBeginDecelerating:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)launchIcon:(id)fp8;
- (void)doubleClickedIcon:(id)fp8;
- (void)clickedIcon:(id)fp8;
- (int)reorderCount;
- (void)incrementReorderCount;
- (void)_addEmptyListIfNecessary;
- (void)setIsEditing:(BOOL)fp8;
- (BOOL)isEditing;
- (id)iconAnimationView;
- (void)moveIconToWindow:(id)fp8;
- (void)moveIconFromWindow:(id)fp8 toIconList:(id)fp12;
- (void)ungrabAnimation:(id)fp8 didFinish:(id)fp12 grabbedIcon:(id)fp16;
- (void)noteDownloadStateChanged;
- (void)noteViewCovered;
- (void)setLastTouch:(id)fp8;
- (void)fixupBouncedIconsAfterIndex:(int)fp8;
- (void)setGrabbedIcon:(id)fp8;
- (id)grabbedIcon;
- (id)destinationIconList;
- (void)cancelScrollTimer;
- (void)scrollLeft;
- (void)scrollRight;
- (void)noteGrabbedIconLocationChangedWithTouch:(id)fp8;
- (void)noteGrabbedIconLocationChangedWithEvent:(id)fp8;
- (void)compactIconsInIconLists:(BOOL)fp8 limitToIconList:(id)fp12;
- (void)animateToNewState:(float)fp8 domino:(BOOL)fp12;
- (void)moveAnimation:(id)fp8 didFinish:(id)fp12 movePlan:(id)fp16;
- (void)moveIcon:(id)fp8 fromIconList:(id)fp12 toX:(int)fp16 Y:(int)fp20 toIconList:(id)fp24 animate:(BOOL)fp28;
- (void)moveIcon:(id)fp8 fromIconList:(id)fp12 toX:(int)fp16 Y:(int)fp20 toIconList:(id)fp24;

@end

