/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, NSMutableDictionary, NSString;

@interface SBImageCache : NSObject
{
    NSString *_path;
    unsigned int _width;
    unsigned int _height;
    unsigned int _imageSize;
    int _fd;
    NSMutableDictionary *_keysToIndexes;
    NSMutableDictionary *_keysToModDates;
    NSMutableArray *_freeList;
    BOOL _dirty;
}

- (id)initWithName:(id)fp8 imageWidth:(unsigned int)fp12 imageHeight:(unsigned int)fp16;
- (void)dealloc;
- (long long)_offsetForIndex:(unsigned int)fp8;
- (id)_metadataPath;
- (id)imageForKey:(id)fp8;
- (id)modificationDateForKey:(id)fp8;
- (void)_markDirty;
- (void)setBitmapImageData:(void *)fp8 forKey:(id)fp12 modificationDate:(id)fp16;
- (void)removeImageForKey:(id)fp8;
- (id)allKeys;
- (void)save;

@end

