/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface SBLaunchdUtilities : NSObject
{
}

+ (BOOL)createJobWithLabel:(id)fp8 path:(id)fp12 arguments:(id)fp16 environment:(id)fp20 standardOutputPath:(id)fp24 standardErrorPath:(id)fp28 machServices:(id)fp32 threadPriority:(long long)fp36 jetsamPriority:(long long)fp44 waitForDebugger:(BOOL)fp52 denyCreatingOtherJobs:(BOOL)fp56 runAtLoad:(BOOL)fp60;
+ (void)deleteJobWithLabel:(id)fp8;
+ (int)pidForLabel:(id)fp8;
+ (int)lastExitStatusForLabel:(id)fp8;
+ (id)allJobLabels;
+ (void)setJetsamPriority:(long long)fp8 forJobLabel:(id)fp16 isFrontmost:(BOOL)fp20;

@end

