/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBAlertItem.h>

@interface SBLockScreenAudioRoutesAlertItem : SBAlertItem
{
}

- (Class)alertSheetClass;
- (id)alertSheet;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (BOOL)allowMenuButtonDismissal;
- (void)willRelockForButtonPress:(BOOL)fp8;
- (BOOL)shouldShowInLockScreen;
- (BOOL)togglesMediaControls;
- (void)performUnlockAction;
- (void)audioRoutingPicker:(id)fp8 didSelectRouteAtIndex:(int)fp12;

@end

