/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class SBApplication, UIWindow;

@interface SBMiniAlertController : NSObject
{
    SBApplication *_displayShowingAnAlert;
    UIWindow *_dimmingWindow;
    unsigned int _miniAlertVisible:1;
}

+ (id)sharedInstance;
- (id)dimImageForKeyboard:(BOOL)fp8;
- (void)showDimmingWindow;
- (void)finishedAnimatingDimWindowOut:(id)fp8 didFinish:(id)fp12;
- (void)cancelHideDimmingWindow;
- (void)hideDimmingWindowAfterDelay;
- (void)hideDimmingWindow;
- (void)deactivateAlertItemsForDisplay:(id)fp8;
- (void)displayWillShowMiniAlert:(id)fp8 fenceId:(unsigned int)fp12;
- (id)displayShowingAnAlert;
- (void)displayWillDismissMiniAlert:(id)fp8 andShowAnother:(BOOL)fp12 fenceId:(unsigned int)fp16;
- (void)displayDidDismissMiniAlert:(id)fp8;
- (void)showApplicationMiniAlertsIfNeeded;
- (void)hideApplicationMiniAlerts;
- (void)noteMiniAlertStateChanged;
- (BOOL)miniAlertVisible;
- (BOOL)canShowAlerts;

@end

