/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBAlertItem.h>

@class NSString;

@interface SBMMSDelayedDownloadAlertItem : SBAlertItem
{
    NSString *_fromAddress;
    int _messageCount;
}

- (void)dealloc;
- (void)setMessage:(id)fp8;
- (void)setMessageCount:(int)fp8;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)_showNetworkPrefs;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;

@end

