/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBFlippyAlertItem.h>

#import <UIKit/UIModalViewDelegate-Protocol.h>

@class MPAudioDeviceController;

@interface SBNowPlayingAlertItem : SBFlippyAlertItem <UIModalViewDelegate>
{
    unsigned int _beganSeeking:1;
    unsigned int _deferLayout:1;
    unsigned int _needsLayout:1;
    MPAudioDeviceController *_audioDeviceController;
}

- (id)init;
- (void)dealloc;
- (id)createCenteredLabel:(BOOL)fp8;
- (void)_updateLabelWithTag:(int)fp8 text:(id)fp12 faded:(BOOL)fp16 cursor:(float *)fp20 sheet:(id)fp24;
- (void)updateInformation;
- (id)_createButtonWithImage:(id)fp8 action:(SEL)fp12 tag:(int)fp16;
- (Class)frontAlertSheetClass;
- (Class)backAlertSheetClass;
- (id)createFrontAlertSheet;
- (id)createBackAlertSheet;
- (void)willActivate;
- (void)willDeactivateForReason:(int)fp8;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)dismissOnLock;
- (BOOL)dimissOnAlertActivation;
- (void)configureFront:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)audioRoutingPicker:(id)fp8 didSelectRouteAtIndex:(int)fp12;
- (void)willPresentModalView:(id)fp8;
- (void)didPresentModalView:(id)fp8;
- (void)_playPauseButtonAction:(id)fp8;
- (void)_changeTrackButtonDown:(id)fp8;
- (void)_changeTrackButtonUp:(id)fp8;
- (void)_changeTrackButtonTouchPause:(id)fp8;
- (void)_volumeChange:(id)fp8;
- (void)_registerForNowPlayingNotifications;
- (void)_unregisterForNowPlayingNotifications;
- (void)_registerForVolumeNotifications;
- (void)_unregisterForVolumeNotifications;
- (void)_nowPlayingChanged:(id)fp8;
- (void)_systemVolumeChanged:(id)fp8;
- (void)audioDeviceControllerAudioRoutesChanged:(id)fp8;
- (void)audioDeviceControllerMediaServerDied:(id)fp8;

@end

