/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIModalView.h>

@class UIButton, UILabel, UISlider;

@interface SBNowPlayingAlertSheet : UIModalView
{
    struct CGRect normalSliderFrame;
    struct CGRect narrowSliderFrame;
    UIButton *routeButton;
    UISlider *volumeSlider;
    UILabel *routeLabel;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)_positionControlButton:(int)fp8 withFloor:(float)fp12;
- (void)showRouteButtonAnimated:(BOOL)fp8;
- (void)hideRouteButtonAnimated:(BOOL)fp8;
- (void)showVolumeSlider;
- (void)hideVolumeSlider;
- (void)layout;
- (id)routeLabel;
- (void)setRouteLabel:(id)fp8;
- (id)routeButton;
- (void)setRouteButton:(id)fp8;
- (id)volumeSlider;
- (void)setVolumeSlider:(id)fp8;
- (struct CGRect)narrowSliderFrame;
- (void)setNarrowSliderFrame:(struct CGRect)fp8;
- (struct CGRect)normalSliderFrame;
- (void)setNormalSliderFrame:(struct CGRect)fp8;

@end

