/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBWaveView.h>

@interface SBPathWaveView : SBWaveView
{
}

+ (Class)layerClass;
- (id)_shapeLayer;
- (id)initWithFrame:(struct CGRect)fp8;
- (BOOL)_shouldAnimatePropertyWithKey:(id)fp8;
- (struct CGPath *)_copyCurrentPath;
- (void)_updateCurrentPath;
- (void)setColor:(id)fp8;
- (void)layoutSubviews;

@end

