/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import <Foundation/NSCoding-Protocol.h>

@class NSData, NSDate, NSDictionary, NSString, SBRemoteNotificationAlert;

@interface SBRemoteNotificationClient : NSObject <NSCoding>
{
    NSString *_bundleIdentifier;
    NSString *_environment;
    int _appEnabledTypes;
    int _settingsEnabledTypes;
    int _settingsPresentedTypes;
    NSData *_lastKnownDeviceToken;
    NSDate *_missingDate;
    BOOL _hasShownSystemwideEnableAlert;
    NSDictionary *_lastUserInfo;
    SBRemoteNotificationAlert *_currentAlertItem;
}

- (id)initWithBundleIdentifier:(id)fp8;
- (void)dealloc;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (int)effectivelyEnabledTypes;
- (id)currentAlertItem;
- (void)setCurrentAlertItem:(id)fp8;
- (id)lastUserInfo;
- (void)setLastUserInfo:(id)fp8;
- (BOOL)hasShownSystemwideEnableAlert;
- (void)setHasShownSystemwideEnableAlert:(BOOL)fp8;
- (id)missingDate;
- (void)setMissingDate:(id)fp8;
- (id)lastKnownDeviceToken;
- (void)setLastKnownDeviceToken:(id)fp8;
- (int)settingsPresentedTypes;
- (void)setSettingsPresentedTypes:(int)fp8;
- (int)settingsEnabledTypes;
- (void)setSettingsEnabledTypes:(int)fp8;
- (int)appEnabledTypes;
- (void)setAppEnabledTypes:(int)fp8;
- (id)environment;
- (void)setEnvironment:(id)fp8;
- (id)bundleIdentifier;

@end

