/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSString, SBApplication, SBProxyRemoteView;

@interface SBRemoteViewInfo : NSObject
{
    NSString *_remoteViewIdentifier;
    SBProxyRemoteView *_proxyRemoteView;
    unsigned int _contextID;
    SBApplication *_application;
    struct CGSize _viewSize;
}

- (void)dealloc;
- (struct CGSize)viewSize;
- (void)setViewSize:(struct CGSize)fp8;
- (id)application;
- (void)setApplication:(id)fp8;
- (id)proxyRemoteView;
- (void)setProxyRemoteView:(id)fp8;
- (unsigned int)contextID;
- (void)setContextID:(unsigned int)fp8;
- (id)remoteViewIdentifier;
- (void)setRemoteViewIdentifier:(id)fp8;

@end

