/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface SBRemoteViewsController : NSObject
{
    NSMutableDictionary *_registeredRemoteViewInfos;
    NSMutableDictionary *_unregisteredRemoteViewInfos;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)unregisterProxyRemoteView:(id)fp8;
- (void)registerRemoteContextID:(unsigned int)fp8 forIdentifier:(id)fp12 size:(struct CGSize)fp16 application:(id)fp24;
- (void)unregisterRemoteIdentifier:(id)fp8 application:(id)fp12;
- (id)_createProxyRemoteViewForIdentifier:(id)fp8;
- (void)_sequesterProxyRemoteView:(id)fp8;
- (id)proxyRemoteViewForIdentifier:(id)fp8;
- (void)unregisterRemoteViewsForApplication:(id)fp8;

@end

