/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import <ApplePushService/APSConnectionDelegate-Protocol.h>

@class NSMutableDictionary, NSString;

@interface SBRemoteNotificationServer : NSObject <APSConnectionDelegate>
{
    NSMutableDictionary *_bundleIdentifiersToClients;
    NSMutableDictionary *_environmentsToConnections;
    unsigned int _lastPlayedAlertSound;
    NSString *_lastNotificationReceivedBundleIdentifier;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)_clientsArchivePath;
- (void)saveClientState;
- (void)_purgeMissingClients;
- (void)run;
- (void)remoteNotificationAlertWasDismissedForApplication:(id)fp8 launched:(BOOL)fp12;
- (void)connection:(id)fp8 didReceivePublicToken:(id)fp12;
- (void)noteApplicationFinishedLaunching:(id)fp8;
- (void)connection:(id)fp8 didReceiveMessageForTopic:(id)fp12 userInfo:(id)fp16;
- (id)_localizedStringFromKey:(id)fp8 defaultValue:(id)fp12 inBundle:(id)fp16 arguments:(id)fp20;
- (void)_playAlertSound:(BOOL)fp8 soundName:(id)fp12 inBundle:(id)fp16;
- (void)stopPlayingAlertSound;
- (id)lastNotificationReceivedBundleIdentifier;
- (id)allAppEnabledTypeValues;
- (id)allSettingsEnabledTypeValues;
- (void)calculateTopics;
- (void)registerApplication:(id)fp8 forEnvironment:(id)fp12 withTypes:(int)fp16;
- (void)unregisterApplication:(id)fp8;
- (int)getEffectiveEnabledTypesForApplication:(id)fp8;
- (BOOL)isSystemwideEnabled;
- (void)setSystemwideEnabled:(BOOL)fp8;
- (BOOL)hasRegisteredBundleIdentifiers;
- (void)setSettingsTypes:(int)fp8 forBundleIdentifier:(id)fp12;
- (id)getMessageUserInfoForBundleIdentifier:(id)fp8;

@end

