/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBAlertItem.h>

@class NSString, SBApplication;

@interface SBRemoteNotificationAlert : SBAlertItem
{
    SBApplication *_app;
    NSString *_body;
    NSString *_actionLabel;
    BOOL _showActionButton;
    BOOL _launched;
}

- (id)initWithApplication:(id)fp8 body:(id)fp12 showActionButton:(BOOL)fp16 actionLabel:(id)fp20;
- (void)dealloc;
- (Class)alertSheetClass;
- (void)activateApplication;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)performUnlockAction;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (id)lockLabel;
- (BOOL)willShowInAwayItems;
- (void)willDeactivateForReason:(int)fp8;

@end

