/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import <SpringBoard/SPDaemonQueryDelegate-Protocol.h>
#import <UIKit/UISearchBarDelegate-Protocol.h>
#import <UIKit/UITableViewDataSource-Protocol.h>
#import <UIKit/UITableViewDelegate-Protocol.h>

@class NSArray, NSDate, NSDateFormatter, NSMutableArray, NSString, NSTimer, SBSearchView, SPDaemonQueryToken, SPSearchResult, SPSearchResultDeserializer;

@interface SBSearchController : NSObject <UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate, SPDaemonQueryDelegate>
{
    SBSearchView *_searchView;
    NSString *_queryString;
    NSDateFormatter *_dateFormatter;
    int _domainOrdering[12];
    NSArray *_querySearchDomains;
    BOOL _querySearchDomainsIncludesApplications;
    int _sectionToGroupMap[12];
    BOOL _sectionToGroupMapIsValid;
    int _resultSectionCount;
    int _applicationsSectionIndex;
    SPSearchResult *_cursor;
    SPSearchResultDeserializer *_resultGroups[12];
    SPSearchResultDeserializer *_accumulatingResultGroups[12];
    char _resultGroupsIsCurrent[12];
    SPDaemonQueryToken *_currentToken;
    NSMutableArray *_matchingLaunchingIcons;
    NSTimer *_clearSearchTimer;
    NSDate *_clearSearchDate;
    BOOL _reloadingTableContent;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)setSearchView:(id)fp8;
- (void)updateSearchOrdering;
- (void)resetClearSearchTimer;
- (void)startClearSearchTimer;
- (void)_updateClearSearchTimerFireDate;
- (void)_clearSearchTimerFired;
- (BOOL)hasQueryString;
- (BOOL)hasSearchResults;
- (void)searchBarTextDidBeginEditing:(id)fp8;
- (void)searchBarTextDidEndEditing:(id)fp8;
- (void)searchBar:(id)fp8 textDidChange:(id)fp12;
- (void)searchBarSearchButtonClicked:(id)fp8;
- (BOOL)_sectionIsApp:(int *)fp8 appOffset:(int *)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)_stringFromDate:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)_deselect;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)updateTableContents;
- (void)searchDaemonQuery:(id)fp8 addedResults:(id)fp12;
- (void)searchDaemonQuery:(id)fp8 encounteredError:(id)fp12;
- (void)searchDaemonQueryCompleted:(id)fp8;
- (BOOL)_shouldDisplayApplicationSearchResults;
- (void)_promoteAccumulatedResults;
- (void)_releaseAccumulatingResultGroups;
- (void)_releaseResultGroups;
- (void)_updateSectionToGroupMap;
- (id)_groupForSection:(int)fp8;
- (int)_groupIndexForSection:(int)fp8;
- (int)_resultSectionCount;
- (id)_launchingURLForResult:(id)fp8 withDisplayIdentifier:(id)fp12;
- (void)_updateApplicationSearchResults;
- (id)_imageForDomain:(int)fp8 andDisplayID:(id)fp12;
- (id)_imageForDisplayIdentifier:(id)fp8;
- (void)clearSearchResults;
- (id)searchView;

@end

