/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class SBApplication, SBProxyRemoteView;

@interface SBSheetView : UIView
{
    SBProxyRemoteView *_remoteProxyView;
    SBApplication *_app;
}

- (id)initWithRemoteViewIdentifier:(id)fp8 application:(id)fp12;
- (id)remoteViewIdentifier;
- (id)application;
- (void)noteSheetDidEnd;
- (void)dealloc;

@end

