/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, UIWindow;

@interface SBSheetController : NSObject
{
    NSMutableDictionary *_appToSheetMap;
    UIWindow *_presentationWindow;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)animateSheetUp:(id)fp8;
- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)animateSheetDown:(id)fp8;
- (BOOL)presentRemoteViewIdentifier:(id)fp8 asSheetForApplication:(id)fp12;
- (void)dismissRemoteViewIdentifier:(id)fp8 forApplication:(id)fp12;
- (BOOL)isShowingSheets;
- (void)dismissAllSheets;
- (void)dismissSheetsForApplication:(id)fp8;
- (BOOL)sheetWantsProgress;

@end

