/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBSlidingAlertDisplay.h>

@class NSString;

@interface SBSIMLockEntryAlertDisplay : SBSlidingAlertDisplay
{
    NSString *_languageCode;
    NSString *_code;
}

- (id)initWithFrame:(struct CGRect)fp8 languageCode:(id)fp24;
- (void)dealloc;
- (id)localizedStringWithKey:(id)fp8;
- (id)_pinAttemptsRemainingLabel;
- (BOOL)alphanumericKeyboard;
- (void)setupUnlockAttemptState;
- (id)failureTitle;
- (id)failureLabel;
- (void)setupFailureState;
- (id)titleText;
- (id)label;
- (void)setupCurrentLockAttemptState;
- (void)alertDisplayWillBecomeVisible;
- (void)setupSuccess;
- (void)_unlock;
- (void)unlock;
- (void)phonePad:(id)fp8 keyUp:(BOOL)fp12;
- (void)passcodeFieldDidAcceptEntry:(id)fp8;

@end

