/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSDate, NSString, NSTimer;

@interface SBSleepProofTimer : NSObject
{
    NSDate *_fireDate;
    id _target;
    SEL _selector;
    NSString *_identifier;
    NSTimer *_timer;
    NSTimer *_preventSleepTimer;
    BOOL _isWakeScheduled;
    void *_powerAssertion;
}

+ (id)scheduledTimerWithFireDate:(id)fp8 target:(id)fp12 selector:(SEL)fp16 identifier:(id)fp20;
- (id)initWithFireDate:(id)fp8 target:(id)fp12 selector:(SEL)fp16 identifier:(id)fp20;
- (void)dealloc;
- (void)_invalidateTimers;
- (void)_scheduleTimers;
- (void)_setWakeScheduled:(BOOL)fp8;
- (void)_holdPowerAssertion:(BOOL)fp8;
- (void)_preventSleepTimerFired:(id)fp8;
- (void)_timerFired:(id)fp8;
- (void)_wokeFromSleep;
- (void)_significantTimeChanged;
- (id)_preventSleepFromDate;
- (id)_wakeDate;
- (id)fireDate;
- (void)cancel;

@end

