/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBApplication.h>

@interface SBSMSApplication : SBApplication
{
}

- (id)defaultImage:(char *)fp8;
- (void)launchSucceeded:(BOOL)fp8;

@end

