/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBStatusBarContentView.h>

@class NSString, UIFont;

@interface SBStatusBarDoubleHeightView : SBStatusBarContentView
{
    NSString *_durationPreamble;
    struct CGSize _durationPreambleSize;
    UIFont *_font;
}

- (id)init;
- (void)dealloc;

@end

