/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBStatusBarContentView.h>

@interface SBStatusBarAirPortView : SBStatusBarContentView
{
    int _dataConnectionType;
    int _signalStrength;
    unsigned int _showsAirPortBars:1;
    unsigned int _showsCellDataIndicator:1;
    unsigned int _isPolling:1;
    unsigned int _didSetIndicatorFlags:1;
    BOOL _showsAirPortView;
    float _overlap;
}

- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (void)setAirPortStrength:(int)fp8;
- (void)setShowsAirPortBars:(BOOL)fp8;
- (void)setShowsCellDataIndicator:(BOOL)fp8;
- (void)setDataConnectionType:(int)fp8;
- (BOOL)showsIndicator;
- (void)dataConnectionTypeChanged;
- (int)priority;
- (void)drawRect:(struct CGRect)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)setVisible:(BOOL)fp8;
- (BOOL)isVisible;
- (float)padding;
- (void)setOverlap:(float)fp8;
- (float)overlap;

@end

