/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIWindow.h>

@class UIView;

@interface SBStatusWindow : UIWindow
{
    UIView *_holderView;
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)holderView;

@end

