/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBStatusBarContentView.h>

@interface SBStatusBarBatteryView : SBStatusBarContentView
{
    int _batteryCapacity;
    float _curvedCapacity;
    BOOL _batteryCharging;
    BOOL _isOnAC;
    BOOL _showBatteryView;
}

- (void)updateBattery;
- (void)_batteryStatusChanged:(id)fp8;
- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (int)priority;
- (void)drawRect:(struct CGRect)fp8;
- (void)setVisible:(BOOL)fp8;
- (BOOL)isVisible;
- (float)padding;

@end

