/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class SBStatusBarContentsView, SBStatusBarDoubleHeightView, SBStatusWindow, UIView;

@interface SBStatusBar : UIControl
{
    int _mode;
    int _orientation;
    SBStatusBarContentsView *_contentsView;
    SBStatusBarDoubleHeightView *_doubleHeightView;
    SBStatusWindow *_statusWindow;
    UIView *_airplaneView;
    UIView *_baseDoubleHeightColorView;
    UIView *_glowDoubleheightColorView;
    UIView *_dimmerView;
    int _doubleHeightMode;
    unsigned int _animating:1;
    unsigned int _glowAnimationEnabled:1;
    unsigned int _isPressed:1;
    unsigned int _airplaneMode:1;
}

- (id)initWithMode:(int)fp8 orientation:(int)fp12;
- (id)description;
- (void)_setGlowImage:(id)fp8;
- (void)_setBaseImage:(id)fp8;
- (void)updateDoubleHeightView;
- (void)setStatusWindow:(id)fp8;
- (id)statusWindow;
- (void)dealloc;
- (int)mode;
- (int)orientation;
- (struct CGAffineTransform)distantStatusWindowTransform;
- (id)contentsView;
- (id)airplaneView;
- (void)drawRect:(struct CGRect)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)start;
- (void)stop;
- (void)showDimmerOverlay:(BOOL)fp8;
- (void)setDimmerOverlayColor:(id)fp8;
- (void)startGlowAnimation;
- (void)stopGlowAnimation;
- (BOOL)isGlowAnimationEnabled;
- (void)setGlowAnimationEnabled:(BOOL)fp8;
- (void)setAirplaneModeIsEnabled:(BOOL)fp8 animate:(BOOL)fp12 ignoreAirPortPower:(BOOL)fp16;
- (void)setAirplaneModeIsEnabled:(BOOL)fp8 animate:(BOOL)fp12;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;
- (BOOL)isDimmed;
- (void)statusBarClicked;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;

@end

