/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray, SBStatusBar, SBStatusBarAirPortView, SBStatusBarBatteryPercentageView, SBStatusBarBatteryView, SBStatusBarBluetoothBatteryView, SBStatusBarBluetoothView, SBStatusBarCallForwardingView, SBStatusBarCarrierView, SBStatusBarNoServiceView, SBStatusBarProgressView, SBStatusBarSignalView, SBStatusBarTimeView, SBStatusBarVPNView;

@interface SBStatusBarContentsView : UIView
{
    SBStatusBar *_statusBar;
    int _mode;
    BOOL _dimmed;
    BOOL _enteringAirplaneMode;
    UIView *_lockIconView;
    SBStatusBarTimeView *_timeView;
    SBStatusBarBatteryView *_batteryView;
    SBStatusBarBatteryPercentageView *_batteryPercentageView;
    SBStatusBarSignalView *_signalView;
    SBStatusBarCarrierView *_carrierView;
    NSMutableArray *_indicatorViews;
    SBStatusBarAirPortView *_airPortView;
    SBStatusBarNoServiceView *_noServiceView;
    SBStatusBarBluetoothView *_bluetoothView;
    SBStatusBarProgressView *_progressView;
    SBStatusBarBluetoothBatteryView *_bluetoothBatteryView;
    SBStatusBarVPNView *_vpnView;
    SBStatusBarCallForwardingView *_forwardingView;
}

+ (float)contentAlphaForMode:(int)fp8;
- (id)initWithStatusBar:(id)fp8 mode:(int)fp12;
- (void)dealloc;
- (id)statusBar;
- (void)buildContentViews;
- (void)updateContentViewsAlpha;
- (void)reflowContentViewsNow;
- (void)reflowContentViews:(BOOL)fp8;
- (void)reflowContentViews;
- (void)stop;
- (void)_initializeIndicatorViewsWithNames:(id)fp8;
- (void)_arrangeIconsByPriorityWithLeftWidth:(float)fp8 rightWidth:(float)fp12;
- (void)_addObjectSortedByPriority:(id)fp8 toArray:(id)fp12;
- (float)_removeViews:(id)fp8 withNeededCapacity:(float)fp12 totalCapacity:(float)fp16;
- (float)_capacityAfterAddingView:(id)fp8 onSide:(id)fp12;
- (void)start;
- (void)bluetoothBatteryAvailabilityChanged;
- (void)stopClock;
- (void)startClock;
- (void)updateClockFormat;
- (void)setShowsService:(BOOL)fp8 SIMStatus:(id)fp12;
- (void)significantTimeChange;
- (void)signalFormatChanged;
- (void)customTextChanged;
- (void)progressChanged;
- (void)cloakChanged;
- (void)showBatteryPercentageChanged;
- (void)setAirPortStrength:(int)fp8;
- (void)setShowsAirPort:(BOOL)fp8 animate:(BOOL)fp12;
- (void)indicatorsChanged;
- (void)airplaneModeAnimationFinished:(id)fp8;
- (void)setIsInAirplaneMode:(BOOL)fp8 animate:(BOOL)fp12 ignoreAirPortPower:(BOOL)fp16;
- (void)setIsInAirplaneMode:(BOOL)fp8 animate:(BOOL)fp12;
- (BOOL)shouldDisplayBatteryPercentage;
- (void)loopCarrierNameIfNecessary;

@end

