/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBStatusBarContentView.h>

@class NSString;

@interface SBStatusBarIndicatorView : SBStatusBarContentView
{
    BOOL _showIndicatorView;
    NSString *_indicatorName;
}

- (id)initWithName:(id)fp8 andMode:(int)fp12;
- (void)dealloc;
- (int)priority;
- (void)setVisible:(BOOL)fp8;
- (BOOL)isVisible;
- (id)indicatorName;
- (id)description;
- (float)padding;

@end

