/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBStatusBarContentView.h>

@interface SBStatusBarBatteryPercentageView : SBStatusBarContentView
{
    int _displayedCapacity;
    BOOL _isOnAC;
    BOOL _showBatteryPercentageView;
}

- (id)init;
- (void)updateBattery;
- (void)_batteryStatusChanged:(id)fp8;
- (void)dealloc;
- (void)start;
- (void)stop;
- (int)priority;
- (void)drawRect:(struct CGRect)fp8;
- (void)setVisible:(BOOL)fp8;
- (BOOL)isVisible;
- (float)padding;

@end

