/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBStatusBarContentView.h>

@class NSString;

@interface SBStatusBarNoServiceView : SBStatusBarContentView
{
    NSString *_errorString;
    BOOL _showNoServiceView;
}

+ (id)displayStringForSIMStatus:(id)fp8;
+ (id)displayStringForRegistrationStatus:(int)fp8;
- (id)initWithErrorString:(id)fp8;
- (id)errorString;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;
- (id)textFont;
- (int)priority;
- (void)setVisible:(BOOL)fp8;
- (BOOL)isVisible;
- (float)padding;

@end

