/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBStatusBarContentView.h>

@interface SBStatusBarSignalView : SBStatusBarContentView
{
    int _raw;
    int _bars;
    int _percentage;
    BOOL _showSignalView;
}

- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (int)priority;
- (void)updateSignalStrength;
- (void)drawRect:(struct CGRect)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)setVisible:(BOOL)fp8;
- (BOOL)isVisible;
- (float)padding;

@end

