/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBStatusBarContentView.h>

@class UIImageView;

@interface SBStatusBarCallForwardingView : SBStatusBarContentView
{
    UIImageView *_imageView;
    BOOL _setOnce;
    BOOL _showIndicator;
    BOOL _showForwardingView;
    BOOL _showOnLeft;
}

- (id)init;
- (void)updateIndicator;
- (void)setShowsIndicator:(BOOL)fp8;
- (BOOL)showsIndicator;
- (void)setMode:(int)fp8;
- (void)dealloc;
- (int)priority;
- (void)setVisible:(BOOL)fp8;
- (BOOL)isVisible;
- (BOOL)showOnLeft;
- (void)setShowOnLeft:(BOOL)fp8;
- (float)padding;

@end

