/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <SpringBoard/SBStatusBarContentView.h>

@interface SBStatusBarBluetoothBatteryView : SBStatusBarContentView
{
    BOOL _showBluetoothBatteryView;
}

- (id)init;
- (void)start;
- (void)stop;
- (void)batteryLevelChanged;
- (void)drawRect:(struct CGRect)fp8;
- (int)priority;
- (void)setVisible:(BOOL)fp8;
- (BOOL)isVisible;
- (float)padding;

@end

