/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface SBTelephonyManager : NSObject
{
    void *_suspendDormancyAssertion;
    NSString *_operatorName;
    unsigned int _suspendDormancyEnabled;
    unsigned int _usingWifi:1;
    unsigned int _usingVPN:1;
    unsigned int _iTunesNeedsToRecheckActivation:1;
    unsigned int _pretendingToSearch:1;
    unsigned int _callForwardingIndicator:2;
    unsigned int _usingWirelessModem:1;
}

+ (id)sharedTelephonyManager;
- (id)init;
- (struct __CTServerConnection *)_serverConnection;
- (void)_serverConnectionDidError:(CDAnonymousStruct2)fp8;
- (void)SBTelephonyDaemonRestartHandler;
- (void)updatePhoneNumberPrefs;
- (void)updateTTYIndicator;
- (double)inCallDuration;
- (void)setCallForwardingIndicator:(int)fp8;
- (void)updateCallForwardingIndicator;
- (int)callForwardingIndicator;
- (void)updateSpringBoard;
- (void)setLimitTransmitPowerPerBandEnabled:(BOOL)fp8;
- (void)setFastDormancySuspended:(BOOL)fp8;
- (void)updateAirplaneMode;
- (void)updateCalls;
- (void)_updateState;
- (BOOL)updateLocale;
- (BOOL)updateNetworkLocale;
- (void)handleSIMReady;
- (id)urlWithScheme:(id)fp8 fromDialingNumber:(id)fp12 abUID:(int)fp16 urlPathAddition:(id)fp20;
- (id)displayForOutgoingCallURL:(id)fp8;
- (void)_delayedAudioResume;
- (long long)getRowIDOfLastCallInsert;
- (id)allMissedCallsAfterRowID:(long long)fp8;
- (int)callCount;
- (BOOL)activeCallExists;
- (BOOL)heldCallExists;
- (BOOL)incomingCallExists;
- (BOOL)outgoingCallExists;
- (BOOL)inCallUsingReceiver;
- (BOOL)callWouldUseReceiver:(BOOL)fp8;
- (BOOL)shouldHangUpOnLock;
- (BOOL)inCall;
- (void)disconnectIncomingCall;
- (void)answerIncomingCall;
- (void)answerIncomingCallEndingOthers;
- (void)swapCalls;
- (void)disconnectAllCalls;
- (void)disconnectCall;
- (void)disconnectCallAndActivateHeld;
- (void)unmute;
- (void)dumpBasebandState:(id)fp8;
- (BOOL)MALoggingEnabled;
- (void)powerOffRadio;
- (BOOL)isNetworkRegistrationEnabled;
- (void)setNetworkRegistrationEnabled:(BOOL)fp8;
- (int)dataConnectionType;
- (BOOL)EDGEIsOn;
- (BOOL)isUsingDataConnection;
- (BOOL)isUsingWiFiConnection;
- (void)setIsUsingWiFiConnection:(BOOL)fp8;
- (void)setIsUsingVPNConnection:(BOOL)fp8;
- (BOOL)isUsingVPNConnection;
- (void)copyICCID:(id *)fp8 IMEI:(id *)fp12;
- (void)configureForTTY:(BOOL)fp8;
- (BOOL)shouldPromptForTTY;
- (id)ttyTitle;
- (void)_resetCTMMode;
- (void)_headphoneChanged:(id)fp8;
- (void)_proximityChanged:(id)fp8;
- (void)_setRegistrationStatus:(int)fp8;
- (void)_updateRegistrationNow;
- (void)_cancelFakeService;
- (void)_startFakeServiceIfNecessary;
- (void)_stopFakeService;
- (BOOL)_pretendingToSearch;
- (id)_fetchOperatorName;
- (void)_reallySetOperatorName:(id)fp8;
- (void)setOperatorName:(id)fp8;
- (void)operatorBundleChanged;
- (id)operatorName;
- (int)registrationStatus;
- (void)checkForRegistrationSoon;
- (id)SIMStatus;
- (int)registrationCauseCode;
- (void)noteSIMUnlockAttempt;
- (BOOL)isUsingWirelessModem;
- (void)setIsUsingWirelessModem:(BOOL)fp8;
- (void)noteWirelessModemChanged;

@end

