/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString, UIColor, UIFont;

@interface SBTextDisplayView : UIView
{
    NSString *_text;
    UIFont *_font;
    UIColor *_fontColor;
}

- (id)initWithWidth:(float)fp8 font:(id)fp12 fontColor:(id)fp16;
- (void)dealloc;
- (void)_updateText;
- (void)setText:(id)fp8;
- (void)setFont:(id)fp8;
- (void)setFontColor:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

