/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class SBZoomView, UIView, UIWindow;

@interface SBUIController : NSObject
{
    UIWindow *_window;
    UIView *_iconsView;
    UIView *_buttonBarContainerView;
    UIView *_contentView;
    SBZoomView *_zoomLayer;
    BOOL _restoringIconList;
    BOOL _lastVolumeDownToControl;
    BOOL _shouldAutoLock;
    float _batteryCapacity;
    float _curvedBatteryCapacity;
    BOOL _isBatteryCharging;
    BOOL _isOnAC;
    BOOL _connectedToUnusableFirewire;
    int _batteryLoggingStartCapacity;
    unsigned char _headsetBatteryCapacity;
    BOOL _isHeadsetCharging;
    BOOL _isHeadsetDocked;
    BOOL _ignoreHeadsetEvents;
}

+ (int)displayedLevelForLockScreenBatteryLevel:(int)fp8;
+ (id)sharedInstance;
- (void)_indicateConnectedToPower;
- (void)dealloc;
- (id)init;
- (void)animateAppleDown:(BOOL)fp8;
- (BOOL)launchedAfterLanguageRestart;
- (void)clearLaunchedAfterLanguageRestart;
- (void)localeChanged;
- (void)languageChanged;
- (void)finishLaunching;
- (void)systemControllerRouteChanged:(id)fp8;
- (void)lock:(BOOL)fp8;
- (void)lock;
- (void)clearZoomLayer;
- (id)contentView;
- (id)window;
- (void)launchIcon:(id)fp8;
- (void)activateApplicationAnimated:(id)fp8;
- (void)showZoomLayerWithDefaultImageOfApp:(id)fp8;
- (void)showZoomLayerWithIOSurfaceSnapshotOfApp:(id)fp8 includeStatusWindow:(id)fp12;
- (void)scatterIconListAndBar:(BOOL)fp8;
- (void)insertAndOrderIconListsForReordering:(BOOL)fp8;
- (void)restoreIconList:(BOOL)fp8;
- (void)animateApplicationActivation:(id)fp8 animateDefaultImage:(BOOL)fp12 scatterIcons:(BOOL)fp16;
- (void)animateApplicationActivationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)tearDownIconListAndBar;
- (void)animateApplicationSuspend:(id)fp8;
- (void)applicationSuspendAnimationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)animateApplicationSuspendFlip:(id)fp8;
- (void)applicationSuspendFlipDidStop:(id)fp8;
- (void)stopRestoringIconList;
- (void)showButtonBar:(BOOL)fp8 animate:(BOOL)fp12 action:(SEL)fp16 delegate:(id)fp20;
- (void)finishedFadingInButtonBar;
- (BOOL)clickedMenuButton;
- (void)wakeUp:(id)fp8;
- (void)handleVolumeEvent:(struct __GSEvent *)fp8;
- (void)updateBatteryState:(id)fp8;
- (float)batteryCapacity;
- (int)batteryCapacityAsPercentage;
- (float)curvedBatteryCapacity;
- (int)curvedBatteryCapacityAsPercentage;
- (BOOL)isBatteryCharging;
- (BOOL)isOnAC;
- (void)ACPowerChanged;
- (void)setIsConnectedToUnusableFirewireCharger:(BOOL)fp8;
- (BOOL)isConnectedToUnusableFirewireCharger;
- (void)noteStatusBarHeightChanged:(float)fp8 duration:(double)fp12;
- (BOOL)isHeadsetDocked;
- (BOOL)isHeadsetBatteryCharging;
- (unsigned char)headsetBatteryCapacity;
- (void)handleAccessoryAvailabilityChange:(struct __GSEvent *)fp8 removal:(BOOL)fp12;
- (void)handleAccessoryEvent:(struct __GSEvent *)fp8;

@end

