/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSTimer;

@interface SBWiFiManager : NSObject
{
    struct __WiFiManagerClient *_manager;
    struct __WiFiDeviceClient *_device;
    struct __WiFiNetwork *_currentNetwork;
    BOOL _currentNetworkHasBeenSet;
    BOOL _powered;
    BOOL _poweredHasBeenSet;
    int _rssiThreshold;
    BOOL _joining;
    int _signalStrengthBars;
    BOOL _signalStrengthHasBeenSet;
    NSTimer *_signalStrengthTimer;
    int _shouldPollSignalStrength;
    BOOL _canPollSignalStrength;
    NSMutableDictionary *_securityDict;
    id _delegate;
    unsigned int _notificationID;
    double _lastSignalStrengthUpdateTime;
}

+ (id)sharedInstance;
+ (BOOL)hasWiFi;
- (void)dealloc;
- (struct __WiFiManagerClient *)_manager;
- (id)init;
- (void)setDelegate:(id)fp8;
- (void)scan;
- (BOOL)joining;
- (void)dismissAlerts;
- (void)_powerStateDidChange;
- (void)_linkDidChange;
- (void)_updateCurrentNetwork;
- (BOOL)isAssociated;
- (BOOL)_cachedIsAssociated;
- (id)currentNetworkName;
- (BOOL)powered;
- (BOOL)wiFiEnabled;
- (void)setWiFiEnabled:(BOOL)fp8;
- (int)signalStrengthBars;
- (void)updateSignalStrength;
- (void)_updateSignalStrengthTimer;
- (void)beginPollingForSignalStrength;
- (void)endPollingForSignalStrength;
- (void)cancelTrust:(BOOL)fp8;
- (void)acceptTrust:(id)fp8;
- (void)cancelPicker:(BOOL)fp8;
- (void)userChoseNetwork:(id)fp8;
- (id)knownNetworks;
- (BOOL)networkRequiresPassword:(id)fp8;
- (void)resetSettings;
- (void)_scanComplete:(struct __CFArray *)fp8;
- (void)_joinComplete:(int)fp8 network:(struct __WiFiNetwork *)fp12;
- (void)joinNetwork:(id)fp8 password:(id)fp12;
- (void)_askToJoinWithID:(unsigned int)fp8;
- (void)_trustCallbackWithID:(unsigned int)fp8 type:(int)fp12 network:(struct __WiFiNetwork *)fp16 data:(id)fp20;

@end

