/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIModalView.h>

@interface SMSAlertSheet : UIModalView
{
    BOOL _showingTagline;
    BOOL _showingImage;
}

- (void)layout;
- (void)setImageData:(id)fp8;
- (BOOL)showingImage;
- (void)updateTagline;
- (void)layoutAnimated:(BOOL)fp8;

@end

