/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol UIAutoscrollContainer
- (struct CGRect)contentFrameForView:(id)fp8;
- (struct CGPoint)autoscrollContentOffset;
- (void)setAutoscrollContentOffset:(struct CGPoint)fp8;
@end

