/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject-Protocol.h>

@protocol UIFormAssistantDelegate <NSObject>
- (void)formAssistant:(id)fp8 didBeginEditingFormNode:(id)fp12;
- (void)formAssistant:(id)fp8 didEndEditingFormNode:(id)fp12;
@end

