/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITextInputTraits-Protocol.h>
#import <UIKit/UITextInputTraits_Private-Protocol.h>
#import <UIKit/UITextSelectingContainer-Protocol.h>

@protocol UIKeyboardInput <UITextInputTraits, UITextInputTraits_Private, UITextSelectingContainer>
- (id)delegate;
- (id)textInputTraits;
- (BOOL)hasContent;
- (id)text;
- (void)setText:(id)fp8;
- (void)deleteBackward;
- (void)insertText:(id)fp8;
- (void)selectAll;
- (int)selectionState;
- (id)keyboardInputView;
- (BOOL)hasSelection;
- (struct CGRect)rectContainingCaretSelection;
- (struct CGRect)rectForNSRange:(struct _NSRange)fp8;
- (id)rectsForNSRange:(struct _NSRange)fp8;
- (id)wordRangeContainingCaretSelection;
- (id)rangeByMovingCurrentSelection:(int)fp8;
- (id)rangeByExtendingCurrentSelection:(int)fp8;
- (void)extendCurrentSelection:(int)fp8;
- (id)wordContainingCaretSelection;
- (id)wordInRange:(id)fp8;
- (unsigned short)characterAfterCaretSelection;
- (unsigned short)characterBeforeCaretSelection;
- (unsigned short)characterInRelationToCaretSelection:(int)fp8;
- (void)expandSelectionToStartOfWordContainingCaretSelection;
- (void)moveBackward:(unsigned int)fp8;
- (void)moveForward:(unsigned int)fp8;
- (void)replaceRangeWithText:(struct _NSRange)fp8 replacementText:(id)fp16;
- (void)replaceCurrentWordWithText:(id)fp8;
- (void)replaceRangeWithTextWithoutClosingTyping:(struct _NSRange)fp8 replacementText:(id)fp16;
- (BOOL)rangeAtSentenceStart:(id)fp8;
- (struct _NSRange)selectionRange;
- (id)selectedDOMRange;
- (void)setSelectedDOMRange:(id)fp8 affinityDownstream:(BOOL)fp12;
- (BOOL)selectionAtDocumentStart;
- (BOOL)selectionAtSentenceStart;
- (BOOL)selectionAtWordStart;
- (struct _NSRange)markedTextRange;
- (id)markedText;
- (void)setMarkedText:(id)fp8 selectedRange:(struct _NSRange)fp12;
- (void)setMarkedText:(id)fp8;
- (void)confirmMarkedText:(id)fp8;
- (int)wordOffsetInRange:(id)fp8;
- (struct CGRect)convertCaretRect:(struct CGRect)fp8;
- (BOOL)isProxyFor:(id)fp8;
- (id)textColorForCaretSelection;
- (id)fontForCaretSelection;
@end

