/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol UIKeyboardEmojiController
- (void)emojiSelected:(id)fp8;
- (id)recents;
- (id)emojiForCodePoint:(id)fp8;
@end

