/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject-Protocol.h>

@protocol UIMovieScrubberTrackViewDataSource <NSObject>
- (double)movieScrubberTrackViewDuration:(id)fp8;
- (id)movieScrubberTrackView:(id)fp8 evenlySpacedTimestamps:(int)fp12 startingAt:(id)fp16 endingAt:(id)fp20;
- (id)movieScrubberTrackView:(id)fp8 timestampsStartingAt:(id)fp12 endingAt:(id)fp16 maxCount:(int)fp20;
- (float)movieScrubberTrackViewThumbnailAspectRatio:(id)fp8;
- (void)movieScrubberTrackView:(id)fp8 requestThumbnailImageForTimestamp:(id)fp12;
@end

