/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject-Protocol.h>

@protocol UITextMagnifier <NSObject>
- (void)beginMagnifyingTarget:(id)fp8 magnificationPoint:(struct CGPoint)fp12 offset:(struct CGPoint)fp20 animated:(BOOL)fp28;
- (void)stopMagnifying:(BOOL)fp8;
- (void)postAutoscrollPoint:(struct CGPoint)fp8;
- (void)setAutoscrollDirections:(int)fp8;
- (void)autoscrollWillNotStart;
- (struct CGPoint)animationPoint;
- (void)setAnimationPoint:(struct CGPoint)fp8;
- (struct CGPoint)offset;
- (void)setOffset:(struct CGPoint)fp8;
- (struct CGPoint)magnificationPoint;
- (void)setMagnificationPoint:(struct CGPoint)fp8;
- (BOOL)terminalPointPlacedCarefully;
- (struct CGPoint)terminalPoint;
- (id)target;
@end

