/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject-Protocol.h>

@protocol UIWebSelectionBlock <NSObject>
- (id)webFrame;
- (struct CGRect)boundingRect;
- (id)parentBlock;
- (id)largerParent;
- (BOOL)isSameBlock:(id)fp8;
- (BOOL)containsBlock:(id)fp8;
- (BOOL)strictlyContainsBlock:(id)fp8;
- (BOOL)rendersAsBlock;
- (BOOL)selectable;
- (id)asDomNode;
- (id)asDomRange;
- (BOOL)containsRange:(id)fp8;
- (BOOL)canShrinkDirectlyToTextOnly;
- (id)rangeOfContents;
- (id)enclosingDocument;
@end

